config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include(('web.urls', 'web'),
                                      namespace='web')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # import debug_toolbar
    # urlpatterns += [
    #     url(r'^__debug__/', include(debug_toolbar.urls)),
    # ]

web/urls.py
from django.conf.urls import url
from .views.system import home, about
from .views.post import post, post_detail
from .views.course import courses

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^post/$', post, name='post'),
    url(r'^cursos/$', courses, name='courses'),
    url(r'^post/detalle/$', post_detail, name='post_detail'),
    url(r'^sobre-mi/$', about, name='about'),
]

apps/base/models.py
from django.db import models
from django.core.cache import cache
from django.utils.translation import ugettext_lazy as _
from .managers import RemovedManager


class TimeModel(models.Model):
    """ Modelo Base"""
    created = models.DateTimeField(_('created'), auto_now_add=True)
    modified = models.DateTimeField(_('modified'), auto_now=True)

    class Meta:
        abstract = True


class PositionModel(models.Model):
    """ Model for position """
    position = models.IntegerField(verbose_name=_('Position'), default=1)

    class Meta:
        verbose_name = _('Position Model')
        verbose_name_plural = _('Position Models')
        abstract = True
        ordering = ['position']


class RemovedModel(models.Model):
    is_removed = models.BooleanField(default=False)
    objects = RemovedManager()


    class Meta:
        verbose_name = "Delete Model"
        verbose_name_plural = "Delete Models"
        abstract = True

    def __str__(self):
        pass


class SingletonModel(models.Model):

    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        self.pk = 1
        super(SingletonModel, self).save(*args, **kwargs)
        self.set_cache()

    @classmethod
    def load(cls):
        if cache.get(cls.__name__) is None:
            obj, created = cls.objects.get_or_create(pk=1)
            if not created:
                obj.set_cache()
        return cache.get(cls.__name__)

    def set_cache(self):
        cache.set(self.__class__.__name__, self.pk)

apps/base/views.py
from django.shortcuts import render

# Create your views here.

templates/common/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Daniel Huamani</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}?v=3">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    {% block css %}

    {% endblock css %}
</head>
<body class="{% block class_body %}{% endblock %}">
    <div class="wrapper">
        {% include "./header.html" %}
        <div class="content_page ">
            {% block content %}

            {% endblock  %}
        </div>
        {% include "./footer.html" %}
    </div>
    <script src='{% static "web/js/jquery.js" %}'></script>
    {% block js %}

    {% endblock js %}
</body>
</html>

templates/common/footer.html
{% load static %}
<footer class='footer'>
    <div class="footer__top">
        <div class="container footer__container">
            <div class="footer__logo">
                <figure>
                    <img src="{% static 'img/daniel-5.png' %}" width="150">
                </figure>
            </div>
            <div class="footer__center">
                <h3 class="footer__title">
                    SIGUEME EN:
                </h3>
                <div class="footer__redes">
                    <a href="" class="footer__redes__github">
                        <i class="fab fa-github"></i>
                    </a>

                    <a href="" class="footer__redes__gitlab">
                        <i class="fab fa-gitlab"></i>
                    </a>
                    <a href="" class="footer__redes__youtube">
                        <i class="fab fa-youtube"></i>
                    </a>
                </div>

            </div>
            <div class="footer__suscribe">
                <form class="form footer__suscribe__form">
                    <div class="form__input">
                        <input type="" placeholder="email" class="footer__suscribe__input" name="">
                    </div>
                    <button class="btn btn--blue footer__suscribe__btn">SUSCRIBITE</button>
                </form>

            </div>
        </div>
    </div>
    <div class="footer__bot">
        <div class="container">
            <p class="text-center footer__bot__rights">
                Derechos reservados 2019
            </p>
        </div>
    </div>
</footer>

templates/common/header.html
{% load static %}
<header class="header">
    <div class="container">
        <img class="header__logo" src="{% static 'img/daniel-4.png' %}">
        <nav class='header__menu'>
            <ul class="header__menu__ul">
                <li>
                    <a href="" class="header__menu__link">Home</a>
                </li>
                <li>
                    <a href="{% url 'web:post' %}" class="header__menu__link">Blog</a>
                </li>
                <li>
                    <a href="{% url 'web:courses' %}" class="header__menu__link">Cursos</a>
                </li>
                <li>
                    <a href="" class="header__menu__link">Sobre mi</a>
                </li>
                <li>
                    <a href="" class="header__menu__link">Contacto</a>
                </li>
            </ul>
        </nav>
    </div>
</header>